# api status message
API_STATUS_MESSAGE_EXPIRED_TOKEN = "EXPIRED_TOKEN"
API_STATUS_MESSAGE_INVALID_SIGNATURE = "INVALID_SIGNATURE"
API_STATUS_MESSAGE_COMMON_TOKEN_ERROR = "COMMON_TOKEN_ERROR"

# api status code
API_STATUS_CODE_BAD_REQUEST = 400
API_STATUS_CODE_UNAUTHORIZED = 401
API_STATUS_CODE_FORBIDDEN = 403
API_STATUS_CODE_NOT_FOUND = 404
API_STATUS_CODE_SERVER_ERROR = 500
API_STATUS_CODE_OK = 200
API_STATUS_CODE_CREATED = 201
