# Generated by Django 3.2 on 2023-01-05 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정 일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='삭제 여부')),
                ('used_amount', models.BigIntegerField(default=0, verbose_name='금액')),
                ('history', models.CharField(blank=True, max_length=255, null=True, verbose_name='사용 내')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_hold_accounts', to='user.user', verbose_name='유저 ID')),
            ],
            options={
                'verbose_name': '가계부 기록',
                'db_table': 'household_account',
            },
        ),
    ]
