# Generated by Django 3.2 on 2023-01-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정 일시')),
                ('email', models.EmailField(db_index=True, max_length=255, null=True, verbose_name='이메일')),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='비밀번호 해쉬값')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
            options={
                'verbose_name': '수정 일시',
                'db_table': 'user',
            },
        ),
    ]
